### ISSUE TITLE
Tags beginning with FF do not appear to be correctly processed

### ISSUE THREAD

**Issue by clownba0t** [Shopify/grizzly_ber#13]
**Steps to Reproduce**

`GrizzlyBer.new("FF0E0101").first.tag`

**Expected**

`FF0E`

**Actual**

`0E`

**Notes**

We currently make use of several tags which begin with `FF` (including `FF0D`, `FF0E` and `FF0F`) in our EMV implementation. Based on my current understanding of the BER-TLV standard (as described in Annex B of EMV 4.3 Book 3), `FF` is permissible as the first byte of a tag:

![image](https://cloud.githubusercontent.com/assets/4664640/10337775/f7fd6eba-6d3c-11e5-956c-978a7c6ee00b.png)

Based on this table, a tag which has a first byte of `FF` (`11111111`) indicates a private, constructed tag which continues in the subsequent bytes.

The source of the issue appears to be here:

https://github.com/Shopify/grizzly_ber/blob/master/lib/grizzly_ber.rb#L63

The byte array representing the TLV is shifted until the first element is neither `0x00` nor `0xFF`. However, based on the BER-TLV standard (as per the table above), `0xFF` would appear to be valid values for the first byte of a tag.

There are several notes on the same page as follows:

> Before, between, or after TLV-coded data objects, '00' bytes without any meaning may occur (for example, due to erased or modified TLV-coded data objects).
> Note: It is strongly recommended that issuers do not use tags beginning with ‘FF’ for proprietary purposes, as existing terminals may not recognise ‘FF’ as the beginning of a constructed private class tag.

As a result, I can understand the removal of any `0x00` values before processing the tag. However, I do feel that perhaps this is not appropriate for the `0xFF` value. What are your thoughts on this?

**Comment by ryanbalsdon** [comment]
Thanks for raising this issue!

I have seen 0xFF used as erasure bytes in the field so this will be tricky to fix. Waiting until a bad tag is detected before trying to drop them might work.

We use context-specific tags instead of private to get around this.

**Comment by clownba0t** [comment]
@ryanbalsdon Thanks for the very quick and kind response.

> I have seen 0xFF used as erasure bytes in the field so this will be tricky to fix. Waiting until a bad tag is detected before trying to drop them might work.

I see what you mean - tricky indeed! Your idea to wait and drop the tags only if they're bad sounds good to me - it might be the only way to elegantly handle the fickle nature of `FF` :)

> We use context-specific tags instead of private to get around this.

Unfortunately the tags beginning with `FF` are imposed upon us by a 3rd party (our EMV implementation is rather complex), so I'm afraid we can't change them.

As it turns out we only ever need to build TLVs using these tags (rather than parsing a hex string with them in it), so it's not a major issue for us by any means - in fact, I only discovered the issue when I was working backwards to double check my work by parsing the hex string produced after building the TLVs.

Many thanks again for your response and this gem, which has saved us a lot of time and effort :)
